# Generated by Django 2.2.3 on 2019-07-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20190722_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(upload_to='user_images/'),
        ),
    ]
